### ISSUE TITLE
Sample app not working in Windows 10

### ISSUE THREAD

**Issue by diasks2** [Shoes3/shoes3#196]
I packaged the following [sample app](https://github.com/diasks2/sample_shoes_app/blob/master/sample3.rb) and tried to install it on Windows 10 (64 bit) [using VirtualBox and the Windows 10 technical preview](http://www.sysprobs.com/install-windows-10-on-virtualbox-and-its-guest-additions) from the [Microsoft site](https://insider.windows.com/) and received the following error (not very helpful I know, sorry):

![windows10 64](https://cloud.githubusercontent.com/assets/1476952/12666908/6b9ec1ee-c688-11e5-8bd7-4d2741015e44.jpg)

**Comment by ccoupe** [comment]
I'm going call on our Windows expert @BackOrder. I haven't played with Win 10 although I understand its 'free beer' now days so a preview might not be the way to go. There is some MSFT site for their browers that provides 30 day licences for all the version of Windows.

**Comment by BackOrder** [comment]
Likely to require compatibility mode. Right click on the executable file, select properties, compatibility tab, check execute this program in compatibility mode for and select a previous version of Windows. See if that works for you. Good luck.

**Comment by diasks2** [comment]
Thanks for the suggestion. I wasn't aware of compatibility mode. However, no luck. The exact same thing happens for any version of Windows I test it on. See the .gif below. The only additional clue I have is that you can see in the video the "Setting up Shoes..." dialog box opens briefly and the progress bar is exactly halfway and then it cuts to the "This app can't run on your PC" message.

![windows](https://cloud.githubusercontent.com/assets/1476952/12672756/e01178e0-c6bb-11e5-99f3-d10032ce98ee.gif)

**Comment by BackOrder** [comment]
Are you trying Shoes or Shoes installer? You may want to download Shoes installer again.

Disable anti-virus. Try compatibility for Windows 7. Try run as administrator also.

It is suggested online to create a second Windows account with administration right. Some rare cases the account has problems.

**Comment by diasks2** [comment]
> Are you trying Shoes or Shoes installer?

I packaged this [sample app](https://github.com/diasks2/sample_shoes_app/blob/master/sample3.rb) on OSX using Shoes 3.3.0 r2329 and tried to run the .exe file as described above.

**Comment by BackOrder** [comment]
Have you tried this sample app on a previous version of Windows? Also, @ccoupe has an habit of packaging windows installers incorrectly. The one hosted on the packaging server might be defective.

**Comment by diasks2** [comment]
Here is a [download of the .exe](https://s3.amazonaws.com/tm-town-desktop-application/sample3.exe). It is working on Windows 7 Home: 

![success](https://cloud.githubusercontent.com/assets/1476952/12675573/900e36ea-c6ce-11e5-81a4-a3992b59fb43.jpg)

**Comment by BackOrder** [comment]
Tried on a Windows 10 machine and it was just fine. I'm suspecting your virtual machine or installation is faulty.

**Comment by diasks2** [comment]
Thanks for testing that @BackOrder. It has helped me to narrow down the issue further. If I first install Shoes on the Windows 10 computer then the packaged app will install and run without any issues. However, if Shoes is not first installed on the computer the above error that started this thread will appear (even though Shoes is included in the packaged app).

So on Windows 10 it seems something is going wrong when trying to install Shoes that is bundled with an app. My first guess would be something related to the firewall. When I went to install Shoes on its own in Windows 10 I was asked if I would give the app access to the network. As the bundled version of a packaged app needs to access the network to download Shoes this may be where it is failing.

**Comment by ccoupe** [comment]
It could be some security setting in Win 10, an app that is bundled with Shoes inside, will install that Shoes in "Program Files  (x86)". 

 As for the firewall/network  access, I don't think Shoes does any network traffic until you use the Packager screen or some of the samples.  I did get the same request on an new Win7 install. The stub that launches however does have the code to do the shoes download (if needed) as so it may be marked as a network user.

**Comment by ccoupe** [comment]
@diasks2 , is this still failing for you?

**Comment by diasks2** [comment]
Yes, as far as I know it is still failing, although I haven't tested it on the latest beta. The workaround is to have the end user install Shoes first...but that kind of defeats the purpose of having Shoes bundled with the package.

**Comment by ccoupe** [comment]
Alas, I can't create a Win 10 VM without using/updating my legal Win 7 to a multi user license for Win 10. Not going to happen.

**Comment by diasks2** [comment]
If you use VirtualBox I linked to a Win 10 technical preview at the top of this thread. That works for testing this issue.

**Comment by ccoupe** [comment]
Having just tried to install a less than official version of Win 10 without an valid activation key and gone through the setup,  I can recreate the top message. Is it because Windows knows it's not activated? Or not running a legal copy or It's a Preview ? Or because I didn't allow it to phone home with my ID or it doesn't like the download site or it could be an api change/bug or link setting  in stub.c . Although @BackOrder  claims it does work for him. 

Until I get an activation key and real download that works, there little point to blindingly trying this or that.  Based on my experience so far, I wouldn't  pay $10 US for a license.  Even Apple isn't so nanny state as this creature.

**Comment by diasks2** [comment]
I can confirm it is an issue on Windows 10 whether it is a preview version or an official version. I believe the reason it worked for @BackOrder is that he already had Shoes installed (unless he can confirm he has successfully installed a packaged app on Windows 10 without first installing Shoes) .

**Comment by ccoupe** [comment]
Because I hate mysteries. The error message appears when the stub in the downloaded full-repack is probably handing off to the "silent" part of the  NSIS installer.  Packaging dnlif does work for Win 10. This an important thing to learn. Also worth noting is that the console window spawned by NSIS to run fc-cache.exe does not close when NSIS is finished. It's very possible the version of NSIS inside a full repack is not new enough for Win 10 or NSIS scripts need updating for Win 10,  Very difficult for me to debug without a good version of Win 10.

**Comment by ccoupe** [comment]
There is a Win 10 setting that allows things to run properly! Sadly it was late at night and I was clicking away mostly in desperation and by the time I saw it working, I forgot what the setting is.

**Comment by ccoupe** [comment]
I suspect there are two or more moving pieces to this bug.  One is you have to have pristine Win 10. If shoes does get installed (and removed later), the bug changes to something else. That suggests  a registry problem with the NSIS uninstaller.

Windows complains that the app doesn't have a MSFT id but that doesn't prevent Shoes from being installed and would be a very inconvenient requirement for casual Shoes packagers.  Probably not the problem but it can't be ruled out. 

NSIS is current (2.46)  but old. The NSIS 3 is beta but does have some Win 10 knowledge. Whether that matters is unknown.  It also fails - see https://github.com/Shoes3/shoes3/issues/204 and can't be build (yet) for linux cross compiling. 

Does it matter that my Windows 10 is unlicensed?  or a Tech preview? It certainly could with such a nanny/tattler like Win 10. 

@diasks2 - you don't have many short term options. - Build your own Shoes. Or use 3.3.1 download if needed and use the win32-shortcut gem inside to remove the Shoes.lnk  from the desktop

**Comment by ccoupe** [comment]
Still collecting data and hypotheses. The observation that the installer dialog box progress bar is at 50% is key. (see platforms/msw/stub.c ) That's the point where the stub.c hands off to the Shoes installer with was just downloaded (dnlif) , or copied from the RT_RCDATA resource #129 (full package). Both work on win7, only dnlif works on Win 10.)  Either way, it may look like virus behavior.

This suggests that something in Win 10 is tracking that download vs RSRC behavior differently than win7. A very likely thing for MSFT to do, For example, the Firefox install is actually a small exe that downloads the much larger Firefox.  That is behavior that  Win 10 might find acceptable since it's so common.

Turn off anti-virus? Doesn't Help. Different Developer settings (both under Settings->Update & Security) - no help but plenty of Clues, none of them inspiring. Just by trying to install a packaged script and failing Win 10 is going to  phone home to Mommy and report the failure and  to update their database  of bad people without signed apps.  The more we try to install the  full re-pack Shoes apps, the more complaints they get against your app (or my test app) 

If that really is the situation,  then there is no acceptable  solution.  Even if I got signed creds for Shoes I couldn't transfer them to your packaged app and even  if I could, I wouldn't for liability reasons. Borg is Borg, AAPL or MSFT, they leap frog each other in closing their platforms to the things that Shoes packaging enables.  I'm sorry to see it vanish since I spent a lot of time making it work again

 @diasks2 - Use download if needed packaging while it still it still works and tell your users that it as a prerequisite platform they need first. OR build your own platfom (Your Shoes) and if the Borgs want you to sign it with their app stores - that's your choice.

**Comment by ccoupe** [comment]
See #212

**Comment by ccoupe** [comment]
After much work and and chasing many rabbit holes I encountering our old  friend FONTCONFIG_FILE.   I'm not likey to do much more work on this issue. Maybe some one else will step in. I've lost the will to care about Windows developers hoping they can keep Shoes secret with simple packaging.  It's not going work because of gtk/fontconfig and a lack of Windows C developers to work on MSFT widgets (7 or so years old).  Perhaps someone else can fix it. I'm done.

**Comment by ccoupe** [comment]
Or I'm  not really done. I really don't like giving up. This https://github.com/Shoes3/exe-shoes project will build a Windows 10 exe from a script directory  that doesn't install Shoes as Shoes.

**Comment by ccoupe** [comment]
IF AND ONLY IF, you are running 3.3.1 r2480+,  without the env var FONTCONFIG_FILE in your system setup , (or have no Shoes at all on that machine)  then try http//walkabout.mvmanila.com/public/share/Ytm-2.exe

**Comment by ccoupe** [comment]
This [article](http://www.infoq.com/news/2016/03/win32-to-UWP?utm_campaign=infoq_content&utm_source=infoq&utm_medium=feed&utm_term=global) suggests my assessment of what Win 10 is doing may be correct. They are tracking your packaged Shoes app behavior.  Notice the signing certificate discussion. 

We can't fix that. Instruct your Win 10 users to install Shoes first, or upi can  package download if needed, or build your own installer via [exe-shoes](https://github.com/Shoes3/exe-shoes).

**Comment by ccoupe** [comment]
This needs to be reopened for discussion.

**Comment by ccoupe** [comment]
@BackOrder found this site [Certum](https://www.certum.eu/certum/cert,offer_en_open_source_cs.xml) which offer code signing for 14 euro (per year is implied) which I consider outrageously over priced for an FOSS project not to mention the currency conversion and verification procedures at their site) - Other certificate vendors may be different.   Even If I was willing to go through those hoops all it does is tell Windows that  Shoes.exe is OK to install. It says nothing about what packaged scripts might do.

From Windows perspective:  Malicious Shoes users could create and package a virus/Trojan and wrap it with The Shoe certificate so there's no improvement in safety for end users - actually it's worse with a Shoes packaged exe because that Shoes certificate provides a false sense of security to the down loader.  Not something I want to be part of. All pain for me and no gain for anybody.

**Comment by BackOrder** [comment]
> 14 euro (per year is implied) 

Confirming what you are saying, it is indeed one year: http://www.certum.eu/certum/cert,offer_cert_comparision_cs.xml

There may be alternatives. Needs investigation.

> From Windows perspective: Malicious Shoes users could create and package a virus/Trojan and wrap it with The Shoe certificate so there's no improvement in safety for end users - actually it's worse with a Shoes packaged exe because that Shoes certificate provides a false sense of security to the down loader. Not something I want to be part of. All pain for me and no gain for anybody.

This is not accurate. You would be the only one to hold the certificate. Nobody else can sign but you. If other needs signing, they should get their own certificate. Having Shoes signed would still lower the antivirus false positives and increase trust from users' deployed Shoes apps and Shoes eBook because the executable files are the same.

**Comment by ccoupe** [comment]
> This is not accurate. You would be the only one to hold the certificate. Nobody else can sign but you. If other people need signing, they should get their own certificate

Perhaps you haven't thought of the simple situation . Consider: Signed Shoes is installed and available at the website.. User writes a Shoes script(s) and packages it "include Shoes" - their scripts and resources  are in a Windows resource as a .shy to be extracted and expanded in a temp dir after Shoes is installed by the NSIS installers  runs the newly installed Shoes. That exe is still  Signed by me. And assumed safe.

Remember, OSX & Linux folks can package up their  scritpt/dir into  a  (proposed) Shoes signed exe.  (by me) . Do they need their own Windows certs in place of mine ? MSFT killed Shoes simple  cross platform packaging. And I suspect AAPL will follow, or maybe it led?. Accept reality.

**Comment by BackOrder** [comment]
As long as users do not modify Shoes signed executable files, it will be considered safe. **You are not responsible for user scripts.** We should in fact expect Shoes users to benefit from your code signing. This is the whole point.

Some changes may invalidate the signing on a given executable. Changing the filename (to hide Shoes) will not but changing the internal resource such as an icon might. As a general statement, Shoes users will not need their own code signing even in a deployment scenario.

Code signing is not a new concept. Both Windows and MacOS X favour code signing whereas Linux platform favours a different security model. Windows might have code signing since Windows 95 or something.

**Comment by ccoupe** [comment]
> As long as users do not modify Shoes signed executable files, it will be considered safe. 

But _they will modify_ the exe when injecting resources when packaging. The script or a shy is in a Windows rsrc - changing the icons too. Several resource names are also changed.  That's how packaging works - copy the Shoe.exe from the website (or their cache), and modify it. (keeping the
NSIS installer resources intact of course) - that is what virus do. We know we're honorable people but..

I've been assuming the certificate get applied by (NSIS or it's ilk) but I'll spend a little research time.

**Comment by BackOrder** [comment]
You are correct about resources. This will be considered as a modification.

Let's over put things back into perspective because most users won't do those modifications. In fact, Numinoes would only need one change to keep the code signing intact: not change the icon resource.

> I've been assuming the certificate get applied by (NSIS or it's ilk) but I'll spend a little research time.

Yes, absolutely. Shoes installer would be signed. Shoes.exe and cshoes.exe would also be signed.

**Comment by BackOrder** [comment]
Have you consider accepting donations for Shoes? 

Some way to alleviate the costs of your spending on the project.

Maybe PayPal or something.

**Comment by ccoupe** [comment]
Donations? Not worth the accounting and tax problems.  I'm trying to stay out of the next higher tax bracket - not this year but the principle exists. 

Two mostly separate issues with signing:
1)  Should Shoes be signed so it doesn't offend the Anti-Virus  nannies. Probably,  if the price is low    enough  and it works with OSX and the effort is reasonable. 

2) How to handle 'normal' shoes users packaging for Win 10 as reported by real users way up top and elsewhere. That's the hard nut to crack. In merge packaging they can/should modify the NSIS script if they want a signed app (or a signed ebook). In the easy Shoes world,  OSX users can't run NSIS without a sh*t load of work, nor can Linux users and it isn't that pleasant for Windows.   Could Shoe include a multi-platform  NSIS gem or ext? I suppose it's possible (but seriously ugly) and even then Joe Scriptor would need a certificate for his "Hi Mon" script.  I see nothing but Pain for everyone

**Comment by BackOrder** [comment]
Code signing is fairly easy on MacOS X and well documented on Apple Developer website.

There comes to a point where "Hi Mon" scripts are just "Hi Mon" scripts. It seems you misunderstand code signing. Nobody is asking Shoes users to code sign their Shoes apps. Code signing is aimed for businesses and trusted sources. Most Shoes users will benefit from **your code signing** as it will make Shoes uses and deployment easier. If they do modify internal resources, they will experience what they currently experience with Shoes (for better or worst).

So the point here is that code signing can't hurt. Worst case scenario is that **some** Shoes users will not benefit from it but still experience the Shoes that exist right now as of December, 12th. Others will enjoy a antivirus friendly, running samples, deployment friendly, etc. kind of Shoes.

**Comment by ccoupe** [comment]
Ugg. The more I learn the less I like code signing.  17 euro/yr is a bargain compared to others  (if the encryption algo/cert  works for Win 7 and 10 and OSX) The hassle however is very unappealing. Seriously, it's not something I want to spend my time on **and** any Shoes scriptwriter who packages (Shoes definition of packaging) that wants to deploy his script in his exe is going to have to jump through the same hoops and expenses.  Outrageous.

I'll be happy to work with someone who wants to take over the Shoes3 project and use their certs and their web server to distribute Shoes. I'd rather do that than code signing. Until then packaging for Windows involves - the real end user downloads Shoes (unsigned). User downloads Shy's.  User somehow gets the needed gems.

**Comment by BackOrder** [comment]
Code signing for me always been automated though a building task for deployment. So it never feel a burden once the task is written.

There are most certainly other priorities for Shoes. We may leave this thread open and revisit at a later time, if necessary. Would that be suitable for you at this time?

**Comment by ccoupe** [comment]
I think I need to modify the packaging code to warn it probably won't work if you select .exe (and modify the wiki and the README.md  and leave the Issue open. If I could put at the top of issue list  (sticky) I would. Windows packaging  worked for couple of years longer than 3.0 so that was good.

**Comment by BackOrder** [comment]
Indeed. We might also rename the thread to something more relevant to code signing. Otherwise create a new issue with a summary and link to this issue. Or perhaps do we need both? The issues are related yet different.

**Comment by BackOrder** [comment]
Reading your [commentary](http://walkabout.mvmanila.com/2016/12/23/state-of-the-shoes-address/) on your blog gives to ponder. One of the suggestions I had before was to have Shoes white listed on antiviruses. It might make a difference, might to be free of charge.

For example, take a look at [Kaspersky white list program](http://usa.kaspersky.com/partners/white-list-program/).

**Comment by BackOrder** [comment]
You might be interested in [Windows Defender Exclusions](https://www.tenforums.com/tutorials/5924-windows-defender-exclusions-add-remove-windows-10-a.html). Shoes installer might be able to add itself to the registry, since it has to be installed with admin rights.

**Comment by BackOrder** [comment]
There are is an interesting blog article with good tips: [Dealing with antivirus false-positives](https://weblog.west-wind.com/posts/2016/Oct/05/Dealing-with-AntiVirus-False-Positives).

The ultimate solution is obviously code signing, as I mentioned before.

The bad news is that Certum now charges nearly twice the price as before - a whooping 28€ for open source project. Kinda feels greedy, isn't it?

**Comment by ccoupe** [comment]
That is an interesting article - reminds of why I'm not likely to jump those hoops.  Fees never go down over time do they? .  Odds are Certum is barely covering their costs.

**Comment by ccoupe** [comment]
I'm pretty crypto-dumb but some Linux packages  use gpg for code signing (like rvm).  I gather the choice of hash algorithms is important to OSX and Windows but if the purpose of code signing is to detect that the 'signed thing' has not not be been modified,[ gpg might work](https://www.gnupg.org/gph/en/manual/x135.html). Or not. How we know?

**Comment by BackOrder** [comment]
This all makes sense in theory but in practice Microsoft forces the developer's hand to buy a code signing certificate. Windows is very unlikely to verify anything else than what the root certificate server will tell it.

Your approach may however reduce some of the false-positives with antiviruses. Perhaps also get a (free of charge) [CAcert certificate](http://www.cacert.org/). Read some about it [here](http://stackoverflow.com/questions/1177552/code-signing-certificate-for-open-source-projects/1178091#1178091).

One of the tips in the article is to use another installer. I am tempted to move away from NSIS Unicode to use [Qt Installer Framework](http://doc.qt.io/qtinstallerframework/) instead. The MSYS2 installer is very clean and doesn't seem to be troublesome. I even wrote a small JavaScript script to allow installing MSYS2 unattended, fairly easy and straightforward. QTIFW is also all in JavaScript, which would be easy to rewrite and maintain. Additionally, QTIFW is also available for Linux and MacOS X.

What do you think?

**Comment by ccoupe** [comment]
Qt Installer is very interesting. On first glance it could fit into the Shoes  build process simply.  Worth investing some time.  User level packaging of their scripts would not be cross platorm (I think) but Win 10 broke that so maybe it's not that important - a huge simplification for Shoe code base.

**Comment by BackOrder** [comment]
NSIS Uincode is showing its age. I'm well versed in using it but it just seems easier to work with QTIFW. And then it will be easier for you too, you won't have to dig into some NSIS mumbo jumbo whenever you want to bring some modifications.

> User level packaging of their scripts would not be cross platorm

Sorry? Using QTIFW won't make any difference to the existing Shoes features. It will seemingly replace NSIS Unicode. NSIS was not cross-platform in the first place. **QTIFW is**, We may even look into integrating it in Shoes so users can roll up their own installers.

**Comment by ccoupe** [comment]
shoes.exe, cshoes.exe and packaging (exerb) know and depend on the names and types of resources in the packaged exe. If those change for a different installer, shoes  has to change.

**Comment by BackOrder** [comment]
Installers are a deployment tool that are just wrapping around an existing application (such as Shoes). The installer itself only know what we tell them and doesn't change the application itself. Such as "this is my app, take these files, add the application to the PATH, create a desktop icon, etc." Shoes itself (shoes.exe, cshoes.exe and packaging) knows nothing about the installer, e.g. it knows nothing about NSIS Unicode and won't know anything about QtIFW either. Business as usual.

**Comment by ccoupe** [comment]
Like I said, the **potential** conlict is which resource names/id/numbers are used by QtIFW produced exe's. Since I don't know, I can't say if it's going to be mildly annoying work or something more. It has promise, I like the promise of updates and optional components . Some website implications there.  A better installer would be good for OSX and Linux (in particular) but I haven't looked at those either for QtIFW

**Comment by BackOrder** [comment]
No conflict. :)

Reading the QtIFW documentation is very interesting. QtIFW allows online installation and updates. This would be a huge advantage over previous installers.

Is `rake installer` will work on MSYS2? I can come up with some QtIFW installer code for you to play with.

**Comment by ccoupe** [comment]
`rake package` is what you want.  Your msys2/task.rb might work. Or you could build the xin7 target by changing your $PATH to use the devkit compilers.

**Comment by ccoupe** [comment]
Code signing for Windows 10 (or OSX) is not going happen for Shoes 3,3. Too expensive in money and time.
