### ISSUE TITLE
Command line help missing or incomplete

### ISSUE THREAD

**Issue by BackOrder** [Shoes3/shoes3#20]
Shoes on Windows will not display command line help when typing **shoes.exe -h**. The new cshoes.exe does indeed display the help as expected. It is recommended to use a _MessageBox_ to display the help on the windowed version of Shoes for Windows.

Additionally, Shoes on MacOS X displays an incomplete version of help when ran from the command line using **Shoes.app/Contents/MacOS/shoes -h** as shown here:

```
Usage: shoes [options] (app.rb or app.shy)
	-m	Open the built-in manual.
	-v	Display version info.
```

Whereas **cshoes.exe -h** on Windows displays a more exhaustive list:
```
Usage: shoes [options] (app.rb or app.shy)
    -m, --manual                     Open the built-in manual.
        --old-package                (Obsolete) Package a Shoes app for Windows,
 OS X and Linux.
        --cobbler                    Maintain Shoes installation
    -p, --package                    Package Shoes App (new)
    -g, --gem                        Passes commands to RubyGems.
        --manual-html DIRECTORY      Saves the manual to a directory as HTML.
        --install MODE SRC DEST      Installs a file.
        --nolayered                  No WS_EX_LAYERED style option.
    -v, --version                    Display the version info.
    -h, --help                       Show this message
```

**Comment by ccoupe** [comment]
If you launch shoes on osx like
`mini:~/Projects/shoes3.2$ ~/build/mavericks/Shoes.app/Contents/MacOS/shoes-launch -h` you get the full command line like cshoes.exe. The downside is your file args have to be absolute paths (~/.... works) and #137. None of the shoes-bin/shoes/shoes methods are pleasing for OSX command line use.  

Using `shoes.exe --console -h` also works so I'm not inclined to fix Windows launcher for shoes.exe as you suggest @BackOrder . I might  explore creating a cshoes (bash script) that OSX users can install in /usr/local/bin. Linux could use something similar. A  Cobbler button could create the bash script based on the user's Shoes location and install the generated script into their $PATH for OSX and Linux.  

For developers:
The source download for those building OSX shoes could also have cshoes bash script without the current troubles with the current shoes-launch. Maybe. I'm not a bash person and OSX command line launching is problematic. 

A little bit of code in the OSX rake file could generate a cshoes script in the build directory since it's not always dist/shoes. We might need to create a cshoes.app structure & info.plist with symlinks to the proper places in the build. That sounds like a plan.

**Comment by ccoupe** [comment]
Wiki article on OSX cshoes: https://github.com/Shoes3/shoes3/wiki/Command-line-for-OSX

3.2.24 is at the beta site, http://walkabout.mvmanila.com/public/shoes

![cobbler-cshoes](https://cloud.githubusercontent.com/assets/222691/9128634/22d14cae-3c89-11e5-808d-7255acc19164.png)
