### ISSUE TITLE
Multiple invocations

### ISSUE THREAD

**Issue by ccoupe** [Shoes3/shoes3#22]
From a blog comment, Luka would like
 
There is something I'd like to suggest in a new version of federales. I'd like it if it had one more option when shoes are started, something like test-mode which would open a new window from where you will start your app. That window will stay opened so you can check your progress with one click. It should be easy to get done, windows like this would open when you click 'test-mode' in the main menu of shoes.

Shoes.app do
  button "Test" do
    load @app
  end
end

**Comment by BackOrder** [comment]
Here is a concrete example calling another Shoes.app within an app. Shoes.APPS list the newly created instance _(Shoes::Types::App "test_script")_ and thus gives access to its methods. Luka should elaborate on the user case to give us a better idea of what a test-mode should look like.

```ruby
Shoes.app(:title => "Reentering", :width => 450, :height => 250) {
   button("test") {
      load "test_script.rb"
      para Shoes.APPS
   }
}
```

**test_script.rb**
```ruby
Shoes.app(:title => "test_script", :width => 450, :height => 250) {
  para "test_script is running."
}
```

**Comment by ProvGANG** [comment]
Well, as I have it in mind, process should be the same as with 'open an app' but you should get a window which keeps running and from there you can reload your script with one click. It means that user chooses script to run and after that 'test-mode' is started from where you can load scripts as many times as you want. Your example is pretty much the thing I was thinking about. So when I find in my app something that doesn't work, I change it my text editor and check my adjustments quickly through 'test-mode'.

**Comment by BackOrder** [comment]
You shall find a small code snippet below that should inspire you on how to implement the test-mode you are seeking for. **Remember, this Shoes app will crash if the loaded script crashes.** You may instead consider that many text editors nowadays allow a basic _edit-compile-run_ cycle for which you would simply have to configure to use shoes.exe and pass the script as a parameter.

```ruby
Shoes.app(:width => 450, :height => 250) {
   button("load") {
      @filename = ask_open_file
   }
   button("test") {
      load @filename if @filename
   }
   button("reload") {
      Shoes.APPS.each { |n|
         unless n.name.eql?("Shoes")
            n.close
            load @filename if @filename
         end
      }
   }
}
```

**Comment by ccoupe** [comment]
What might be interesting is a reload button on the Shoes console. I don't know how much effort that would be.  As @BackOrder mentions, a crash in the app or a call to exit() will bring Shoes down.

**Comment by ProvGANG** [comment]
@BackOrder -<h5>That's sort of it.</h5>Of course, any shoes window opened would crash if the other one has crashed, at least that's my experience. <b>I do use a command line also</b> to do the same thing but I thought maybe <b>it would be nice to have such feature.</b>

**Comment by BackOrder** [comment]
The usefulness of this feature is unclear to me and it seems to belong to an IDE. You may be interested to know that I am using NetBeans to develop Shoes applications. Let me know if you would like a walkthrough.

The code above does not guarantee the objects created by the loaded script will be terminated nor garbage collected. Also, during writing the tests for your request, it became clear that there is no way to traverse the contents of a Shoes.app (it seems that events and contents are only implemented in Shoes slots), which may prevent interactions between the loading script and the loaded script.

An important consideration is deployment because when you deploy a Shoes application, you deploy its entire development environment (Shoes console, Shoes manual, etc).

The positive side is that there is a file selector to load scripts already implemented in Shoes, press **alt-.** (alt-dot). It is more likely to do the proper cleaning between reloads. It might be possible to reuse the code to implement the feature you requested.

Please, Cecil and I appreciate feedback and contributions to Shoes, so how about joining us in our quest to make Shoes better?

**Comment by ProvGANG** [comment]
I'd really like to help with shoes in any way if it is possible as I'm not
an expert in programming. Also I'm using just a text editor with syntax
highlighting when it comes to writing in Ruby. I've never tried NetBeans
and if it is useful it would be great to cope with it. Thanks for your
explanations, I thought maybe it would be nice, but yeah that's probably a
job for an IDE. However, it'd be nice if one day Shoes IDE comes up.

2015-01-10 3:06 GMT+01:00 BackOrder <notifications@github.com>:

> The usefulness of this feature is unclear to me and it seems to belong to
> an IDE. You may be interested to know that I am using NetBeans to develop
> Shoes applications. Let me know if you would like a walkthrough.
>
> The code above does not guarantee the objects created by the loaded script
> will be terminated nor garbage collected. Also, during writing the tests
> for your request, it became clear that there is no way to traverse the
> contents of a Shoes.app (it seems that events and contents are only
> implemented in Shoes slots), which may prevent interactions between the
> loading script and the loaded script.
>
> An important consideration is deployment because when you deploy a Shoes
> application, you deploy its entire development environment (Shoes console,
> Shoes manual, etc).
>
> The positive side is that there is a file selector to load scripts already
> implemented in Shoes, press *alt-.* (alt-dot). It is more likely to do
> the proper cleaning between reloads. It might be possible to reuse the code
> to implement the feature you requested.
>
> Please, Cecil and I appreciate feedback and contributions to Shoes, so how
> about joining us in our quest to make Shoes better?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Shoes3/shoes/issues/22#issuecomment-69433469>.
>



-- 
*Cheers!*

**Comment by BackOrder** [comment]
This feature request can stay open here and might eventually be done. Cecil did seem to like the idea. Which text editor are you using? I might be able to help you improve the process of editing and running.

You sure can do a great deal of contributions even though you are not an expert in programming. For example, you can file bug reports whenever you encounter one. Check first if it is already on the issue tracker, add information if necessary, or otherwise file your own report. You can check other reports to know what is desirable (explanation, test scenario, screenshots, code sample, etc).

**Comment by ccoupe** [comment]
Shoes was part of an IDE called HacketyHack.  They were separated into two projects. HH does start on Shoes 3.2 and appears to work but I haven't done any testing of it. It is completely unmaintained by anyone nor do I have intentions to do so. I do provided a download of the last copy I could find at http://shoes.mvmanila.com/public/hh in hh.shy or hh.tar.gz.

**Comment by BackOrder** [comment]
@ProvGANG It seems that you are using Notepad++. NppExec allows you to run external commands, something you might be interested in: http://npp-wiki.iwi.me/index.php/External_Programs. Shoes allows a filename to be passed as a parameter on command line.

**Comment by BackOrder** [comment]
Once NppExec installed, go in NppExec > Execute (or press **F6**) and copy the following command: **cmd.exe /C ""C:\Program Files (x86)\Shoes\Shoes.exe" "$(FULL_CURRENT_PATH)""**  

Click on the drop box and type **Running Shoes** and then click ***Save...*** Ready to launch your Ruby scripts when you press **F6** and **OK** button or **ENTER**.

**Comment by ccoupe** [comment]
I'm closing this issue. Shoes isn't an IDE even though some might think so.  Note: I like Atom for a text editor on OSX, Windows and even Linux. I don't run Shoes from it but I suspect it's doable.
