### ISSUE TITLE
No error in Shoes console  if video path is wrong.

### ISSUE THREAD

**Issue by ccoupe** [Shoes3/shoes3#223]
From the mailing list:  Reported for OSX but it affects all. 
```
Shoes.app  width: 640, height: 480, title: "Der kleine Sheltie" do
  require 'shoes/videoffi'
  Vlc.load_lib
  @stk = stack do
      @vid = video("/Users/ccoupe/Projects/shoes3/Tests/AnemicCinema1926marcelDuchampCut.mp4", autoplay: true)
  end
  @stk.finish {@vid.stop}
end
```
Since that is a  hardcoded path it should fail for anyone else - no Shoe Console error although the launch terminal may complain a lot - not everyone use a terminal and OSX is dead quiet.

**Comment by passenger94** [comment]
that was intentional
- path = "" allows to create an empty widget ready to accept a media with path= method
- i was hoping that user checks for existence of File !, reason why loaded returns nul

your fix doesn't work with n° 1 !
n°2, ok better that way, let's have a guard against wrong media if provided

**Comment by passenger94** [comment]
i was wondering if we shouldn’t hide the `Vlc.load_lib` call  into Shoes::VideoVlc.new now that the Cobbler handles this, that way only the require is needed

**Comment by ccoupe** [comment]
One less line of code for users. I  like it.
