### ISSUE TITLE
Plot captions are not drawn properly

### ISSUE THREAD

**Issue by BackOrder** [Shoes3/shoes3#315]
Run Plot samples in the manual using **Run this** button. Captions are misplaced. The captions are correctly placed **after* change focus and come back to the plot window.

![image](https://cloud.githubusercontent.com/assets/8844578/22908766/4aefcc3c-f21e-11e6-827d-a27ef2d7e191.png)

**Comment by ccoupe** [comment]
Some progress on this. Because plots calculates the pixel position of everything and attempts to store those positions in a shared struct for other functions to use,  it is sensitive to the order of those function calls and the speed of the system and the os graphics redraw signals .  However, samples/good/good-plots.rb fails to display the boundary box (line and scatter) on Linux and Windows - probably osx too.

Caption bug was different. Only Windows showed it. Sigh.

**Comment by ccoupe** [comment]
Shoes 3.3.3 (beta) fixes this.
