### ISSUE TITLE
app.opacity  is not cross plaform

### ISSUE THREAD

**Issue by ccoupe** [Shoes3/shoes3#350]
On Linux, opacity depends on the version of GTK installed. There is no way Shoes can control what gtk3 is currently in use on a Linux users system. We can't build & distribute Shoes/Linux that depends on it. For example, Debian 7.11 is not that old and appears to be using gtk 3.4.2.   Shoes shouldn't be that library version dependent. 

A way forward would be for the user/script-writer to test if the feature exists which requires some way at Shoes lauch time to determine the users libgtk version and somehow create the shoes/ruby method (can't depend on gcc being installed either so ruby-inline may not work and how you would know that at launch time? - already a slow process.

This got checked into the master branch as part of #333 instead of being a separate branch/merge/pull-request. I have to remove it from master . There's a copy  remote branch 'opacity' should anyone want to pursue the very hard work. 

 app.decoration also needs some  testing and should be a separate issue with much more testing before moving in to the master branch.

**Comment by BackOrder** [comment]
How about checking gtk version at runtime? http://stackoverflow.com/questions/126141/how-do-you-find-out-which-version-of-gtk-is-installed-on-ubuntu/16402135#16402135

**Comment by ccoupe** [comment]
You can.  Then what?  The shoes image does have the call compiled (it wasn't available to the build).

**Comment by BackOrder** [comment]
As suggested before, we should consider incremental features propagation. Why can't we have it on Windows and MacOS X for now? It's not a major feature. Eventually a solution for other platforms will come up.

**Comment by ccoupe** [comment]
> we should consider incremental features propagation

Why not have 10 versions of Shoes 3.3.4,  all different in their abilities? Or 40 versions?  How would you describe that in the manual?  "This only works on Win 10".  Who is going to build them, test them and maintain them and host them and how would a user know which to install?  You might have noticed that C is not a dynamic language - there is nothing incremental about it.

**Comment by BackOrder** [comment]
What are you talking about... Software have platform specific features all the time. Ruby for Windows doesn't have fork. They still release Ruby with fork on Linux. They don't let a good feature to go to waste.

A static compiling with `#ifdef` instructions to the preprocessor would do just fine, like any other cross-platform software. Manual would state which platform(s) is supporting the feature. Why do you feel the need to turn everything into a fight?

**Comment by ccoupe** [comment]
Their is one approach that might work on Linux but it's ugly and I don't personally see the value of this particular feature being worth the this:.  Create a file & task  that has the two gtk_get/set_opacity stub functions functions.  Compile/link it as an .so when building Shoes but _Do Not_ link it into libshoes.so. Ick. Then when shoes inits gtk on the user's system. it checks the  gtk version and dloads that library to satisfy the calls later.  That _might_ work  You probably  need to do it on Shoes Windows as well because the older mingw deps (currently in use) may not be new enough.  Pushed out to 3.3.4 or later.

> Ruby for Windows doesn't have fork

One more time: Shoes is not Ruby ;-) For a Shoes widget/method there should be reasonable implementations for all platforms. There's all kinds of linux only things that could be included and osx only things and windows only things that would make it more appealing to those classes of users.

**Comment by BackOrder** [comment]
> RE: dynamic linking

Indeed, this approach would work.

> One more time: Shoes is not Ruby ;-)

You are missing the point. There is no cross-platform software in the world that is fully cross-platform. Some minor features here and there are missing, tweaked or sometimes different. Sometimes even major features are missing. The famous [Write once, run anywhere](https://en.wikipedia.org/wiki/Write_once,_run_anywhere) is not entirely so. Don't get me started on JavaME...

> For a Shoes widget/method there should be reasonable implementations for all platforms. There's all kinds of linux only things that could be included and osx only things and windows only things that would make it more appealing to those classes of users.

No doubt about it. Shoes should ideally be uniform across all platform.

We are currently talking about a feature that Linux supports right now. It may have to be disabled by default because it requires a specific GTK version that is not guaranteed on the host system but it would still be possible for Linux users to build their own Shoes with the feature enabled. In fact, it is fairly standard practice to build packages on *NIX platforms rather than using binary packages. And general Linux users are likely to update to a newer GTK within the next 2 years.

**Comment by ccoupe** [comment]
> We are currently talking about a feature that Linux supports right now

**Some** Lnux support opacity- I have 3 chroot's that don't (and perhaps one VM that will)  and I suspect the current xwin7 target doesn't either.
 
Linux users willing to build from source and distribute their Shoes implementation can do so. Just a few  #ifdefs to change. Whether their end users gtk work or not, would not be my issue. Or would it?  I haven't seen much willingness to do that (OSX and Windows included) and I have been in touch with some said there were unwilling to work that hard.  Not a large enough to sample set to be definitive but enough to know they don't to want fix things if someone else can do it for them. 

We are back to the question of what Shoe is. A teaching tool? A development tool that uses Ruby that _mustl_  work on other platforms or a  development tool  that _might_ work on other platforms .  must  and might is our difference here. I'm in in "must" camp. There's plenty of ways to get platform specific things done. We include Ruby's  win32 gen on Windows builds.  OSX and Linux folks can include gems for their desired extra-Shoes functionality as they wish. 

Opacity and decoration fit in that in-between world.  Perhaps we should write a gem to do opacity instead of building it into Shoes.

**Comment by BackOrder** [comment]
It may have once been a teaching tool. Shoes is a prototyping tool for me. It's a tool to equip game characters for dredknight. What is it to you?

You are the maintainer. So you either include this feature or you don't. Opacity feature is not a deal breaker.

**Comment by dredknight** [comment]
I dont want to further flame around this discussion but I have reached to the conclusion that the best and the worst things on this planet are the abstract one.  Full abstractness gives the ability to do everything one desires. The problem comes when one should convert the abstract knowledge into practical know-how in some area in order to create something and this is skill, while it can be taught to some extent, that is not given to everyone.

Abstractness is both the strength and weakness of Shoes. Every user see it through its own perspective (unlike Photoshop for example which is app created by many people and 100 times more refined than Shoes. But its usage is limited to a very narrow field).

It is easy to lose your way when making something abstract because you dont know if the feature you do is going to be of any use to someone because Shoes (no offense) does not specialize in anything specific and... I love it for this :).

**Comment by ccoupe** [comment]
>  Full abstractness gives the ability to do everything one desires. The problem comes when one should convert the abstract knowledge into practical know-how in some area in order to create something and this is skill, while it can be taught to some extent, that is not given to everyone.

It's called 'Wisdom', and only gained by learning from failure. And, some us fail to remember our lessons.
 
For instance,   gtk_window_set_opacity was a gtk option way back in gtk2.  In gtk 3.8 they changed the name to gtk_widget_set_opacity and deprecated the old name. Calling the old name still works. It gets a compiler warning (or not depending on your setup), but it works and **opacity** is out of the dog house for now. Still needs an ffi and gem based solution that would be future proof when Gtk3 deprecates and/or change the api (seen both). In this case, because it's the app->window, we can get away with ignoring the new api.

**Comment by ccoupe** [comment]
> It may have once been a teaching tool. Shoes is a prototyping tool for me. It's a tool to equip game characters for dredknight.

Relax, it's only a discussion.  It wasn't that long ago that  Shoes  was an cross platform app development **platform** for your game/app  and we worked to hide the Shoes-ness. I happen to think that is worthy goal and Shoes should only as cross platform as possible.

>What is it to you?

It's was a  distraction while I waited to learn if my  cancer was eradicated. That crisis has past, now it just a hobby.

**Comment by BackOrder** [comment]
I am unsatisfied because nearly everything we talk about is met with resistance. We should instead be looking for solutions and bounce ideas off each other. We both have decades of experience and hard, complicated, challenging, breaking things up, etc. should not scare any of us. Nothing ain't stopping us.

> I happen to think that is a worthy goal and Shoes should only as cross platform as possible and platform specific behavior can be added as gem - and we have lots of ways of adding gems.

You mentioned this several times. This is a worthy idea. It may not be necessary to go as far as implementing gems but we should be able to get some of the things out. You seem to have a clear vision for this. Perhaps you could provide a concrete example that would make it easier for us to continue.

My experiments of late involved moving C/Ruby code to Ruby side. For example, it would be possible to define all Shoes classes and methods in Ruby. We still attach the C low level functions to their Ruby method counterparts using FFI or Fiddle. This actually works well but some critical C functions are difficult to hook because they uses `-1` (C calling convention) instead of `-2` (Ruby calling convention) as discussed here — ffi/ffi/issues/569. 

The full advantages are unclear yet. This is the reason why I am reluctant to convert RUBY_M/FUNC_M to Ruby calling convention. But... having classes defined on the Ruby side of Shoes would make it easier to fix and improve things without the need to recompile Shoes each time. It would be easier to fix Shoes DSL (say, remember self thing?), allow nested DSL, add features, unit test, etc. Easier for those who don't know C. And, finally, getting closer to Shoes4 implementation (everything is in Ruby).

> It's was a distraction while I waited to learn if my cancer was eradicated. That crisis has past, now it's just a hobby.

Please, don't let me spoil your hobby nor from enjoying your retirement.

**Comment by passenger94** [comment]
Reaching stratospheric levels of stupidity now !
Hey, let's make Shoes4-bis, but for the fun of it let's do it the deconstructivism avant-garde way and start from the guts of some smart puzzling C ! And of course, the real poetry unleashes at the moment you claim to be unsatisfied !!! Man, you're a genius, Thanks :-D

@cecil, sincerely thank you very much, i learned a lot from you !!!
Have fun.
bye @dredknight !

**Comment by ccoupe** [comment]
stay connect @passenger94, please. It's only a discussion
