### ISSUE TITLE
Radio buttons and checkboxes are clumsy

### ISSUE THREAD

**Issue by ccoupe** [Shoes3/shoes3#87]
Consider 
```ruby
stack {
  button "ok"  {do stuff}
  flow { radio :settings;  para  "Default"}
  flow { radio :settings;  para "Special stuff" }
}
```
button make sense but what is with all the crud surrouiding radio? Why not 
```ruby
radio "Default",  :group => :settings
radio "Special stuff", :group => :settings
```
check (box)  would be similar.  No need for para or flows. When was the last time you wanted the button title on a different line than the checkbox or radio icon? It's always a flow. Presumably the para is used so the user can style the text with a different font or style. When did you last do that on a radio or check? 

This proposal would break compatibility with Shoes 3.1 and Shoes 4 (I think).

**Comment by BackOrder** [comment]
The suggestion is sound but there is a major caveat: What happens when a user wants something else than text besides their radio buttons? Perhaps images. Perhaps group boxes with more elements. Or simply the text on the left rather than on the right of the button.

Granted these are not typical scenarios, they are well within the spirit of Shoes. It might also be more challenging to implemented additional styles to your suggestion than fixing the original issue.

**SAMPLES**
![image](https://cloud.githubusercontent.com/assets/8844578/6787750/3b97f870-d16b-11e4-9c71-e7808d66594a.png)

![image](https://cloud.githubusercontent.com/assets/8844578/6787761/4f0e4d50-d16b-11e4-9259-f5fd77f5097a.png)

![image](https://cloud.githubusercontent.com/assets/8844578/6787779/52e6ebd0-d16b-11e4-9e7c-558fa4105585.png)

![image](https://cloud.githubusercontent.com/assets/8844578/6787783/568d5e40-d16b-11e4-9e7e-480ccbfb4082.png)

**Comment by ccoupe** [comment]
Indeed, there are many things to consider. If we do this.  There are more important things for now.

**Comment by BackOrder** [comment]
Here is a meaningful suggestion, if you are truly considering changing the radio buttons:

```ruby
radio :settings do
   flow { image "folder.png"; para "Shoes box" }
end
```

**Comment by ccoupe** [comment]
I also noticed that radio groups are more like named shoes slots.  A rewrite is a lot of work and probably for little gain.

**Comment by BackOrder** [comment]
> A rewrite is a lot of work and probably for little gain.

We are in agreement.

**Comment by passenger94** [comment]
why not : (just a draft) 
```ruby
class CustomRadio < Shoes::Widget
    def initialize(text, options={})
        group = options[:team] || nil
        icon = options[:icon] || nil
        
        image *icon if icon
        radio group
        para text
    end
end

Shoes.app do
    stack do
       custom_radio "first" , :team => :gr1, :icon => ["#{DIR}/static/icon-info.png", margin: [5,6,2,0]]
       custom_radio "second" , :team => :gr1
       custom_radio "third" , :team => :gr1
    end
end
```
![custom_radio](https://cloud.githubusercontent.com/assets/10730930/7187141/f5a4e19a-e46e-11e4-9f89-408ff13084f1.jpg)

**Comment by ccoupe** [comment]
Closing the the issue.  Custom Widget (assuming it works) is the better place to fix it.
